import {
  AimOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  AuditOutlined,
  BarChartOutlined,
  BellOutlined,
  BookOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  CloudOutlined,
  CloudServerOutlined,
  ClusterOutlined,
  CodeOutlined,
  CommentOutlined,
  CompassOutlined,
  ContactsOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DownloadOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  FieldTimeOutlined,
  FileDoneOutlined,
  FileOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FilterOutlined,
  FlagOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FundProjectionScreenOutlined,
  GlobalOutlined,
  HddOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PictureOutlined,
  PieChartOutlined,
  ProfileOutlined,
  ProjectOutlined,
  QuestionCircleOutlined,
  RadarChartOutlined,
  ReadOutlined,
  ReloadOutlined,
  RiseOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShopOutlined,
  SlidersOutlined,
  StarOutlined,
  SwapOutlined,
  SyncOutlined,
  TableOutlined,
  TagOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TruckOutlined,
  UploadOutlined,
  UserAddOutlined,
  UsergroupAddOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WarningOutlined,
} from '@ant-design/icons';
import type { ReactNode } from 'react';

/**
 * 前端已注册的导航图标：名称 → 组件与中文名。
 *
 * 数据库的 sys_menu.icon_name 只存名称，后端 RegisteredIcons 保存同一份清单用于校验；
 * 新增图标必须两侧同时登记（与 route key 的约定一致）。菜单引用了未登记的名称时
 * 回落到调用方默认图标并在控制台告警，不会把导航渲染成空白。
 */
export interface RegisteredIcon {
  name: string;
  label: string;
  icon: ReactNode;
}

export const appIcons: RegisteredIcon[] = [
  { name: 'TeamOutlined', label: '团队', icon: <TeamOutlined /> },
  { name: 'UserOutlined', label: '用户', icon: <UserOutlined /> },
  { name: 'UserAddOutlined', label: '新增用户', icon: <UserAddOutlined /> },
  { name: 'UsergroupAddOutlined', label: '用户组', icon: <UsergroupAddOutlined /> },
  { name: 'ContactsOutlined', label: '通讯录', icon: <ContactsOutlined /> },
  { name: 'IdcardOutlined', label: '证件', icon: <IdcardOutlined /> },
  { name: 'CustomerServiceOutlined', label: '客服', icon: <CustomerServiceOutlined /> },
  { name: 'AuditOutlined', label: '审计', icon: <AuditOutlined /> },
  { name: 'SafetyCertificateOutlined', label: '安全认证', icon: <SafetyCertificateOutlined /> },
  { name: 'SafetyOutlined', label: '安全', icon: <SafetyOutlined /> },
  { name: 'LockOutlined', label: '权限', icon: <LockOutlined /> },
  { name: 'KeyOutlined', label: '密钥', icon: <KeyOutlined /> },
  { name: 'EyeOutlined', label: '查看', icon: <EyeOutlined /> },
  { name: 'ScanOutlined', label: '扫描', icon: <ScanOutlined /> },
  { name: 'MenuOutlined', label: '菜单', icon: <MenuOutlined /> },
  { name: 'AppstoreOutlined', label: '应用', icon: <AppstoreOutlined /> },
  { name: 'ApartmentOutlined', label: '组织架构', icon: <ApartmentOutlined /> },
  { name: 'ClusterOutlined', label: '集群', icon: <ClusterOutlined /> },
  { name: 'DeploymentUnitOutlined', label: '部署单元', icon: <DeploymentUnitOutlined /> },
  { name: 'PartitionOutlined', label: '分组', icon: <PartitionOutlined /> },
  { name: 'ProjectOutlined', label: '项目', icon: <ProjectOutlined /> },
  { name: 'BuildOutlined', label: '楼宇', icon: <BuildOutlined /> },
  { name: 'BookOutlined', label: '字典手册', icon: <BookOutlined /> },
  { name: 'ReadOutlined', label: '阅读', icon: <ReadOutlined /> },
  { name: 'ProfileOutlined', label: '档案', icon: <ProfileOutlined /> },
  { name: 'FileOutlined', label: '文件', icon: <FileOutlined /> },
  { name: 'FileTextOutlined', label: '文本文件', icon: <FileTextOutlined /> },
  { name: 'FileSearchOutlined', label: '档案检索', icon: <FileSearchOutlined /> },
  { name: 'FileDoneOutlined', label: '办结文件', icon: <FileDoneOutlined /> },
  { name: 'FolderOutlined', label: '文件夹', icon: <FolderOutlined /> },
  { name: 'FolderOpenOutlined', label: '打开文件夹', icon: <FolderOpenOutlined /> },
  { name: 'InboxOutlined', label: '收件箱', icon: <InboxOutlined /> },
  { name: 'DatabaseOutlined', label: '数据库', icon: <DatabaseOutlined /> },
  { name: 'TableOutlined', label: '数据表', icon: <TableOutlined /> },
  { name: 'DashboardOutlined', label: '仪表盘', icon: <DashboardOutlined /> },
  { name: 'BarChartOutlined', label: '柱状统计', icon: <BarChartOutlined /> },
  { name: 'LineChartOutlined', label: '折线趋势', icon: <LineChartOutlined /> },
  { name: 'PieChartOutlined', label: '占比分析', icon: <PieChartOutlined /> },
  { name: 'AreaChartOutlined', label: '面积趋势', icon: <AreaChartOutlined /> },
  { name: 'RadarChartOutlined', label: '雷达分析', icon: <RadarChartOutlined /> },
  {
    name: 'FundProjectionScreenOutlined',
    label: '分析大屏',
    icon: <FundProjectionScreenOutlined />,
  },
  { name: 'RiseOutlined', label: '增长趋势', icon: <RiseOutlined /> },
  { name: 'MonitorOutlined', label: '监控', icon: <MonitorOutlined /> },
  { name: 'DesktopOutlined', label: '终端', icon: <DesktopOutlined /> },
  { name: 'CloudOutlined', label: '云', icon: <CloudOutlined /> },
  { name: 'CloudServerOutlined', label: '服务器', icon: <CloudServerOutlined /> },
  { name: 'HddOutlined', label: '存储', icon: <HddOutlined /> },
  { name: 'ApiOutlined', label: '接口', icon: <ApiOutlined /> },
  { name: 'GlobalOutlined', label: '网络', icon: <GlobalOutlined /> },
  { name: 'NodeIndexOutlined', label: '节点', icon: <NodeIndexOutlined /> },
  { name: 'ClockCircleOutlined', label: '时间', icon: <ClockCircleOutlined /> },
  { name: 'ScheduleOutlined', label: '计划任务', icon: <ScheduleOutlined /> },
  { name: 'CalendarOutlined', label: '日历', icon: <CalendarOutlined /> },
  { name: 'FieldTimeOutlined', label: '工时', icon: <FieldTimeOutlined /> },
  { name: 'HistoryOutlined', label: '历史', icon: <HistoryOutlined /> },
  { name: 'SyncOutlined', label: '同步', icon: <SyncOutlined /> },
  { name: 'ReloadOutlined', label: '刷新', icon: <ReloadOutlined /> },
  { name: 'BellOutlined', label: '通知', icon: <BellOutlined /> },
  { name: 'NotificationOutlined', label: '公告', icon: <NotificationOutlined /> },
  { name: 'MessageOutlined', label: '消息', icon: <MessageOutlined /> },
  { name: 'CommentOutlined', label: '评论', icon: <CommentOutlined /> },
  { name: 'SendOutlined', label: '发送', icon: <SendOutlined /> },
  { name: 'MailOutlined', label: '邮件', icon: <MailOutlined /> },
  { name: 'EnvironmentOutlined', label: '位置', icon: <EnvironmentOutlined /> },
  { name: 'CompassOutlined', label: '方位', icon: <CompassOutlined /> },
  { name: 'AimOutlined', label: '目标', icon: <AimOutlined /> },
  { name: 'FlagOutlined', label: '标记', icon: <FlagOutlined /> },
  { name: 'HomeOutlined', label: '首页', icon: <HomeOutlined /> },
  { name: 'SettingOutlined', label: '设置', icon: <SettingOutlined /> },
  { name: 'ToolOutlined', label: '工具', icon: <ToolOutlined /> },
  { name: 'SlidersOutlined', label: '参数', icon: <SlidersOutlined /> },
  { name: 'ExperimentOutlined', label: '试验', icon: <ExperimentOutlined /> },
  { name: 'BugOutlined', label: '缺陷', icon: <BugOutlined /> },
  { name: 'CodeOutlined', label: '代码', icon: <CodeOutlined /> },
  { name: 'LinkOutlined', label: '链接', icon: <LinkOutlined /> },
  { name: 'ShareAltOutlined', label: '分享', icon: <ShareAltOutlined /> },
  { name: 'SwapOutlined', label: '流转', icon: <SwapOutlined /> },
  { name: 'BranchesOutlined', label: '分支', icon: <BranchesOutlined /> },
  { name: 'SearchOutlined', label: '检索', icon: <SearchOutlined /> },
  { name: 'FilterOutlined', label: '筛选', icon: <FilterOutlined /> },
  { name: 'UploadOutlined', label: '上传', icon: <UploadOutlined /> },
  { name: 'DownloadOutlined', label: '下载', icon: <DownloadOutlined /> },
  { name: 'ImportOutlined', label: '导入', icon: <ImportOutlined /> },
  { name: 'ExportOutlined', label: '导出', icon: <ExportOutlined /> },
  { name: 'EditOutlined', label: '编辑', icon: <EditOutlined /> },
  { name: 'FormOutlined', label: '表单', icon: <FormOutlined /> },
  { name: 'ThunderboltOutlined', label: '任务', icon: <ThunderboltOutlined /> },
  { name: 'StarOutlined', label: '收藏', icon: <StarOutlined /> },
  { name: 'TagOutlined', label: '标签', icon: <TagOutlined /> },
  { name: 'PaperClipOutlined', label: '附件', icon: <PaperClipOutlined /> },
  { name: 'PictureOutlined', label: '图片', icon: <PictureOutlined /> },
  { name: 'VideoCameraOutlined', label: '视频', icon: <VideoCameraOutlined /> },
  { name: 'WarningOutlined', label: '警示', icon: <WarningOutlined /> },
  { name: 'CheckCircleOutlined', label: '完成', icon: <CheckCircleOutlined /> },
  { name: 'InfoCircleOutlined', label: '说明', icon: <InfoCircleOutlined /> },
  { name: 'QuestionCircleOutlined', label: '帮助', icon: <QuestionCircleOutlined /> },
  { name: 'ShopOutlined', label: '站点', icon: <ShopOutlined /> },
  { name: 'TruckOutlined', label: '运输', icon: <TruckOutlined /> },
  { name: 'MoneyCollectOutlined', label: '费用', icon: <MoneyCollectOutlined /> },
  { name: 'CalculatorOutlined', label: '核算', icon: <CalculatorOutlined /> },
];

const byName = new Map(appIcons.map((registered) => [registered.name, registered]));

/** 图标名称是否有可用组件；选择器用它过滤「后端有、前端还没注册」的条目。 */
export function hasRegisteredIcon(name: string): boolean {
  return byName.has(name);
}

/** 未登记的名称返回 undefined 并告警：调用方用默认图标兜底，不把节点渲染成空白。 */
export function iconByName(name: string | null | undefined): ReactNode | undefined {
  if (!name) return undefined;
  const registered = byName.get(name);
  if (!registered) {
    console.warn(`菜单引用了未注册的图标：${name}`);
    return undefined;
  }
  return registered.icon;
}

/** 菜单节点优先用数据库配置的图标；没配置或名称未登记时用调用方给的默认图标。 */
export function resolveIcon(
  name: string | null | undefined,
  fallback?: ReactNode,
): ReactNode | undefined {
  return iconByName(name) ?? fallback;
}
