#!/bin/bash
set -euo pipefail

# Passwords are generated as hex by setup. Reject arbitrary SQL interpolation.
if [[ ! "$MYSQL_APP_PASSWORD" =~ ^[a-f0-9]{48}$ ]]; then
  printf 'MYSQL_APP_PASSWORD must be generated by scripts/dev.sh setup.\n' >&2
  exit 1
fi

MYSQL_PWD="$MYSQL_ROOT_PASSWORD" mysql --protocol=socket --user=root <<SQL
CREATE USER 'merine_app'@'%' IDENTIFIED BY '$MYSQL_APP_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON merine_rebuild.* TO 'merine_app'@'%';
SQL
