-- owner: maritime 涉海基础档案；独立于单位树与账号。无物理外键。

CREATE TABLE archive_port (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案主键，API 返回十进制字符串',
    name VARCHAR(120) NOT NULL COMMENT '档案显示名称，不作为唯一标识',
    region VARCHAR(120) NOT NULL COMMENT '所在区域，公开地理或行政区域文字',
    location VARCHAR(200) NULL COMMENT '位置描述，NULL 表示未提供',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '启停状态：ENABLED 启用、DISABLED 停用，停用保留已有关系',
    source_url VARCHAR(1000) NULL COMMENT '公开参考资料 URL，NULL 表示未提供',
    source_date DATE NULL COMMENT '公开资料发布日期，未知为 NULL，不等同当前名录',
    checked_date DATE NULL COMMENT '公开资料查阅日期，未查阅为 NULL',
    purpose VARCHAR(200) NULL COMMENT '用途说明，NULL 表示未提供',
    fixture_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '本地固定样例唯一键，初始化后不可编辑，普通新建为 NULL',
    version INT NOT NULL DEFAULT 0 COMMENT '并发编辑版本，每次成功修改加一',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时刻，UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最近修改时刻，UTC，由修改 SQL 显式更新',
    PRIMARY KEY (id),
    UNIQUE KEY uk_archive_port_fixture (fixture_key),
    CONSTRAINT ck_archive_port_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_archive_port_version CHECK (version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='maritime 模块：港口基础档案';

CREATE TABLE archive_wharf (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案主键，API 返回十进制字符串',
    name VARCHAR(120) NOT NULL COMMENT '档案显示名称，不作为唯一标识',
    region VARCHAR(120) NOT NULL COMMENT '所在区域，公开地理或行政区域文字',
    location VARCHAR(200) NULL COMMENT '位置描述，NULL 表示未提供',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '启停状态：ENABLED 启用、DISABLED 停用，停用保留已有关系',
    source_url VARCHAR(1000) NULL COMMENT '公开参考资料 URL，NULL 表示未提供',
    source_date DATE NULL COMMENT '公开资料发布日期，未知为 NULL，不等同当前名录',
    checked_date DATE NULL COMMENT '公开资料查阅日期，未查阅为 NULL',
    purpose VARCHAR(200) NULL COMMENT '用途说明，NULL 表示未提供',
    port_id BIGINT NULL COMMENT '所属港口，引用 archive_port.id，由 maritime 写事务锁与删除保护保证完整性；独立码头为 NULL',
    police_station_id BIGINT NULL COMMENT '所属或管辖派出所，引用 archive_police_station.id，由 maritime 写事务锁与删除保护保证完整性',
    responsible_officer_id BIGINT NULL COMMENT '主要责任民警，引用 archive_port_officer.id，由 maritime 写事务锁校验同所及删除保护保证完整性；未指定为 NULL',
    jurisdiction_basis VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '管辖依据：UNVERIFIED 待核实、PUBLIC_REFERENCE 公开资料、DEMO 演示关系',
    jurisdiction_source_url VARCHAR(1000) NULL COMMENT '管辖关系公开依据 URL，PUBLIC_REFERENCE 时必填，其余可为 NULL',
    fixture_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '本地固定样例唯一键，初始化后不可编辑，普通新建为 NULL',
    version INT NOT NULL DEFAULT 0 COMMENT '并发编辑版本，每次成功修改加一',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时刻，UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最近修改时刻，UTC，由修改 SQL 显式更新',
    PRIMARY KEY (id),
    UNIQUE KEY uk_archive_wharf_fixture (fixture_key),
    CONSTRAINT ck_archive_wharf_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_archive_wharf_version CHECK (version >= 0),
    KEY idx_archive_wharf_port_id (port_id, id),
    KEY idx_archive_wharf_police_station_id (police_station_id, id),
    KEY idx_archive_wharf_responsible_officer_id (responsible_officer_id, id),
    CONSTRAINT ck_archive_wharf_basis CHECK (jurisdiction_basis IN ('UNVERIFIED','PUBLIC_REFERENCE','DEMO')),
    CONSTRAINT ck_archive_wharf_public CHECK (jurisdiction_basis <> 'PUBLIC_REFERENCE' OR jurisdiction_source_url IS NOT NULL),
    CONSTRAINT ck_archive_wharf_officer CHECK (responsible_officer_id IS NULL OR police_station_id IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='maritime 模块：码头基础档案';

CREATE TABLE archive_anchorage (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案主键，API 返回十进制字符串',
    name VARCHAR(120) NOT NULL COMMENT '档案显示名称，不作为唯一标识',
    region VARCHAR(120) NOT NULL COMMENT '所在区域，公开地理或行政区域文字',
    location VARCHAR(200) NULL COMMENT '位置描述，NULL 表示未提供',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '启停状态：ENABLED 启用、DISABLED 停用，停用保留已有关系',
    source_url VARCHAR(1000) NULL COMMENT '公开参考资料 URL，NULL 表示未提供',
    source_date DATE NULL COMMENT '公开资料发布日期，未知为 NULL，不等同当前名录',
    checked_date DATE NULL COMMENT '公开资料查阅日期，未查阅为 NULL',
    purpose VARCHAR(200) NULL COMMENT '用途说明，NULL 表示未提供',
    fixture_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '本地固定样例唯一键，初始化后不可编辑，普通新建为 NULL',
    version INT NOT NULL DEFAULT 0 COMMENT '并发编辑版本，每次成功修改加一',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时刻，UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最近修改时刻，UTC，由修改 SQL 显式更新',
    PRIMARY KEY (id),
    UNIQUE KEY uk_archive_anchorage_fixture (fixture_key),
    CONSTRAINT ck_archive_anchorage_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_archive_anchorage_version CHECK (version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='maritime 模块：锚地基础档案';

CREATE TABLE archive_island (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案主键，API 返回十进制字符串',
    name VARCHAR(120) NOT NULL COMMENT '档案显示名称，不作为唯一标识',
    region VARCHAR(120) NOT NULL COMMENT '所在区域，公开地理或行政区域文字',
    location VARCHAR(200) NULL COMMENT '位置描述，NULL 表示未提供',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '启停状态：ENABLED 启用、DISABLED 停用，停用保留已有关系',
    source_url VARCHAR(1000) NULL COMMENT '公开参考资料 URL，NULL 表示未提供',
    source_date DATE NULL COMMENT '公开资料发布日期，未知为 NULL，不等同当前名录',
    checked_date DATE NULL COMMENT '公开资料查阅日期，未查阅为 NULL',
    inhabitation_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '居住类型：INHABITED 有人岛、UNINHABITED 无人岛；历史资料保留资料日期',
    fixture_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '本地固定样例唯一键，初始化后不可编辑，普通新建为 NULL',
    version INT NOT NULL DEFAULT 0 COMMENT '并发编辑版本，每次成功修改加一',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时刻，UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最近修改时刻，UTC，由修改 SQL 显式更新',
    PRIMARY KEY (id),
    UNIQUE KEY uk_archive_island_fixture (fixture_key),
    CONSTRAINT ck_archive_island_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_archive_island_version CHECK (version >= 0),
    CONSTRAINT ck_archive_island_type CHECK (inhabitation_type IN ('INHABITED','UNINHABITED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='maritime 模块：海岛基础档案';

CREATE TABLE archive_police_station (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案主键，API 返回十进制字符串',
    name VARCHAR(120) NOT NULL COMMENT '档案显示名称，不作为唯一标识',
    region VARCHAR(120) NOT NULL COMMENT '所在区域，公开地理或行政区域文字',
    location VARCHAR(200) NULL COMMENT '位置描述，NULL 表示未提供',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '启停状态：ENABLED 启用、DISABLED 停用，停用保留已有关系',
    source_url VARCHAR(1000) NULL COMMENT '公开参考资料 URL，NULL 表示未提供',
    source_date DATE NULL COMMENT '公开资料发布日期，未知为 NULL，不等同当前名录',
    checked_date DATE NULL COMMENT '公开资料查阅日期，未查阅为 NULL',
    fixture_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '本地固定样例唯一键，初始化后不可编辑，普通新建为 NULL',
    version INT NOT NULL DEFAULT 0 COMMENT '并发编辑版本，每次成功修改加一',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时刻，UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最近修改时刻，UTC，由修改 SQL 显式更新',
    PRIMARY KEY (id),
    UNIQUE KEY uk_archive_police_station_fixture (fixture_key),
    CONSTRAINT ck_archive_police_station_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_archive_police_station_version CHECK (version >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='maritime 模块：派出所基础档案';

CREATE TABLE archive_port_officer (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案主键，API 返回十进制字符串',
    name VARCHAR(120) NOT NULL COMMENT '档案显示名称，不作为唯一标识',
    status VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '启停状态：ENABLED 启用、DISABLED 停用，停用保留已有关系',
    source_url VARCHAR(1000) NULL COMMENT '公开参考资料 URL，NULL 表示未提供',
    source_date DATE NULL COMMENT '公开资料发布日期，未知为 NULL，不等同当前名录',
    checked_date DATE NULL COMMENT '公开资料查阅日期，未查阅为 NULL',
    police_station_id BIGINT NOT NULL COMMENT '所属或管辖派出所，引用 archive_police_station.id，由 maritime 写事务锁与删除保护保证完整性',
    duty VARCHAR(120) NULL COMMENT '民警职务说明，NULL 表示未提供',
    is_mock BOOLEAN NOT NULL COMMENT '是否合成民警：1 演示、0 非合成，不采集个人联系方式',
    fixture_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '本地固定样例唯一键，初始化后不可编辑，普通新建为 NULL',
    version INT NOT NULL DEFAULT 0 COMMENT '并发编辑版本，每次成功修改加一',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时刻，UTC',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '最近修改时刻，UTC，由修改 SQL 显式更新',
    PRIMARY KEY (id),
    UNIQUE KEY uk_archive_port_officer_fixture (fixture_key),
    CONSTRAINT ck_archive_port_officer_status CHECK (status IN ('ENABLED','DISABLED')),
    CONSTRAINT ck_archive_port_officer_version CHECK (version >= 0),
    KEY idx_archive_port_officer_police_station_id (police_station_id, id),
    CONSTRAINT ck_archive_port_officer_mock CHECK (is_mock IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='maritime 模块：民警基础档案';
