-- 助手执行记录：每次执行一行，用于「我的历史与用量」以及失败排查；引用完整性由应用层保证。
CREATE TABLE ai_chat_run (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '执行 UUID',
  user_id BIGINT NOT NULL COMMENT '发起用户',
  conversation_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '所属会话，引用 ai_conversation.id',
  idempotency_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '客户端幂等键；同一用户内唯一，重复提交不会产生第二行',
  message_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '助手消息标识，与消息表一致',
  generation_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '追问代次；非追问轮次为空',
  mode VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '执行模式 PROVIDER/DEMO',
  provider_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '供应商配置标识快照',
  provider_name VARCHAR(80) NOT NULL DEFAULT '' COMMENT '连接名称快照，连接改名或删除后仍可追溯',
  model_id VARCHAR(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '模型标识快照',
  reasoning_effort VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '推理强度档位；空表示未使用档位参数',
  state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '终态 SUCCEEDED/AWAITING_INPUT/FAILED/ABORTED',
  error_code VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT '失败错误码；成功为空',
  error_message VARCHAR(300) NOT NULL DEFAULT '' COMMENT '失败文案，截断保存；不含凭据与正文',
  started_at DATETIME(6) NOT NULL COMMENT '开始时间 UTC',
  finished_at DATETIME(6) NOT NULL COMMENT '结束时间 UTC',
  duration_ms INT NOT NULL COMMENT '执行耗时毫秒',
  input_chars INT NOT NULL DEFAULT 0 COMMENT '请求消息总字符数（不保存正文）',
  output_chars INT NOT NULL DEFAULT 0 COMMENT '本次输出字符数',
  prompt_tokens INT NULL COMMENT '上游返回的输入 token 数；上游未返回时为 NULL',
  completion_tokens INT NULL COMMENT '上游返回的输出 token 数；上游未返回时为 NULL',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '写入时间 UTC',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_chat_run_idempotency (user_id, idempotency_key),
  INDEX idx_ai_chat_run_owner (user_id, started_at, id),
  INDEX idx_ai_chat_run_conversation (conversation_id, started_at),
  CONSTRAINT ck_ai_chat_run_state CHECK (state IN ('SUCCEEDED','AWAITING_INPUT','FAILED','ABORTED')),
  CONSTRAINT ck_ai_chat_run_mode CHECK (mode IN ('PROVIDER','DEMO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='agent模块：助手执行记录；含用量与失败原因，不含正文';
